# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7279f1059c2943264d20fd8b4f0e59797359d3de1b7c8474bf829f1de4b480a22750836e7c85a748719766bcc93e509b55fe628df42d73fe64e049913ed7e68

test:
  secret_key_base: e36581671c02ec68a5f4a7bd5d88ae1d99d378c9b50fdb1d1428eb2bac298f0ff8d71c14783181b223fa7dc4c69e63321555cc8afd27fd861bba70a62f50a69e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
